name: autozone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  kfx_dependency_injection: ^1.6.0
  flutter_verification_code: ^1.1.7
  material_symbols_icons: ^4.2671.0
  shared_preferences: ^2.2.1
  freezed: ^2.4.2
  dio: ^5.3.2
  sms_otp_auto_verify: ^2.1.0
  dropdown_button2: ^2.3.9
  sms_autofill: ^2.3.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.1.14
  firebase_database: ^10.2.6
  firebase_core: ^2.16.0
  uuid: ^3.0.7
  firebase_messaging: ^14.6.8
  image_picker: ^1.0.4
  connectivity: ^3.0.6
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/Background.png
    - assets/Sms.png
    - assets/Car.png
    - assets/DocIcon.png
    - assets/LoadingCar.png
    - assets/Document.png
    - assets/Warning.png
    - assets/Mitsubishi.png
    - assets/WorkHours.png
    - assets/Map.png
    - assets/ParkingSign.png
    - assets/Logo/
    - assets/Navigation/
    - assets/Message/
    - assets/UploadImage.png
    - assets/Settings/
    
